# Generated by Django 3.1.3 on 2021-01-20 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='nonamed series', max_length=255)),
                ('episodes', models.IntegerField(default=0)),
                ('prefix', models.CharField(default='noname', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='empty', max_length=255)),
                ('artist', models.CharField(default='Angerfist', max_length=255)),
                ('genre', models.CharField(default='electronic', max_length=255)),
                ('track', models.FileField(upload_to='files/audio')),
            ],
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('artist', models.CharField(default='Angerfist', max_length=255)),
                ('pic', models.ImageField(upload_to='files/image')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.series')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.track')),
            ],
        ),
    ]
