# Generated by Django 3.1.3 on 2021-01-21 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_podcast_series_track'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txt', models.FileField(blank=True, upload_to='')),
                ('tracks', models.ManyToManyField(to='web.Track')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.playlist')),
            ],
        ),
    ]
