# Generated by Django 3.1.3 on 2021-01-22 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_playlist_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='picture',
            field=models.ImageField(default='files/image/default.jpg', upload_to='files/image'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='pic',
            field=models.ImageField(blank=True, upload_to='files/image'),
        ),
    ]
