# Generated by Django 3.1.3 on 2021-01-23 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20210122_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='QTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numinq', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('np', models.IntegerField(default=0)),
                ('end', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='station',
            name='playlist',
        ),
        migrations.RemoveField(
            model_name='station',
            name='url',
        ),
        migrations.AddField(
            model_name='station',
            name='hostname',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='station',
            name='mount',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='station',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='station',
            name='port',
            field=models.TextField(blank=True, max_length=10),
        ),
        migrations.DeleteModel(
            name='Playlist',
        ),
        migrations.AddField(
            model_name='queue',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.station'),
        ),
        migrations.AddField(
            model_name='qtrack',
            name='queue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.queue'),
        ),
        migrations.AddField(
            model_name='qtrack',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.track'),
        ),
    ]
